
FROM python:3.11-slim
WORKDIR /app
COPY requirements.txt ./
RUN pip install --no-cache-dir streamlit==1.39.0 plotly==5.24.1 requests==2.32.3 python-dotenv==1.0.1
COPY frontend ./frontend
COPY src ./src
EXPOSE 8501
CMD ["streamlit","run","frontend/streamlit_app.py","--server.port=8501","--server.address=0.0.0.0"]
